import { describe,it,expect,afterEach } from 'vitest';
import request from 'supertest';
import { fixture,saleInput,addUser } from './helpers.js';
import { createSale,quoteSale } from '../server/sales.js';
import { one,all,integrity,type DB } from '../server/core.js';
import { applyPrices } from '../server/products.js';
import { createApp } from '../server/app.js';
let db:DB;afterEach(()=>db?.close());
describe('Atomic sales and tender accounting',()=>{
 it('posts split payment, price/cost snapshots, change and stock in one transaction',()=>{const f=fixture();db=f.db;const result=db.transaction(()=>createSale(db,f.a,saleInput(f.p,f.sessionId)))();expect(result.total_cents).toBe(30000);expect(result.change_cents).toBe(5000);expect(one(db,'SELECT quantity,value_cents FROM inventory WHERE product_id=?',f.p.id)).toMatchObject({quantity:18,value_cents:180000});expect(all(db,'SELECT * FROM payments')).toHaveLength(2);expect(integrity(db).ok).toBe(true);});
 it('rolls back the whole sale on a duplicate payment reference',()=>{const f=fixture();db=f.db;db.transaction(()=>createSale(db,f.a,saleInput(f.p,f.sessionId)))();expect(()=>db.transaction(()=>createSale(db,f.a,saleInput(f.p,f.sessionId)))()).toThrow();expect(one(db,'SELECT COUNT(*) n FROM sales')!.n).toBe(1);expect(one(db,'SELECT quantity FROM inventory WHERE product_id=?',f.p.id)!.quantity).toBe(18);expect(integrity(db).ok).toBe(true);});
 it('rejects unset prices, forged prices, payment mismatch, negative and excess stock',()=>{const f=fixture();db=f.db;const b=saleInput(f.p,f.sessionId);expect(()=>createSale(db,f.a,{...b,expected_total:'299'})).toThrow(/total/);expect(()=>createSale(db,f.a,{...b,items:[{...b.items[0],unit_price_cents:1}]})).toThrow();expect(()=>createSale(db,f.a,{...b,items:[{...b.items[0],quantity:100}]})).toThrow(/stock/);expect(()=>createSale(db,f.a,{...b,items:[{...b.items[0],quantity:-1}]})).toThrow();const other=one(db,'SELECT * FROM products WHERE id<>? LIMIT 1',f.p.id)!;expect(()=>createSale(db,f.a,{...b,items:[{...b.items[0],product_id:other.id,version:other.version}]})).toThrow(/price/);});
 it('keeps snapshots when current prices change',()=>{const f=fixture();db=f.db;db.transaction(()=>createSale(db,f.a,saleInput(f.p,f.sessionId)))();applyPrices(db,f.a,[{product_id:f.p.id,version:2,cost:'100',selling:'999.99',wholesale:null,promo:null,tax_mode:'none',tax_bps:0}],'Manual price change test');expect(one(db,'SELECT unit_price_cents FROM sale_items')!.unit_price_cents).toBe(15000);expect(()=>db.prepare('UPDATE sales SET total_cents=1').run()).toThrow(/immutable/);expect(()=>db.prepare('DELETE FROM payments').run()).toThrow(/immutable/);});
 it('prevents unauthorised discounts and another user session',()=>{const f=fixture();db=f.db;const cashier=addUser(db,f.a,'cashier');expect(()=>quoteSale(db,cashier,{items:[{product_id:f.p.id,quantity:1,version:2,price_type:'retail'}],discount:'1',discount_reason:'Test discount'})).toThrow(/permission/);expect(()=>createSale(db,cashier,saleInput(f.p,f.sessionId))).toThrow(/own cash session/);});
 it('deduplicates an identical HTTP checkout and rejects changed retry bodies',async()=>{const f=fixture();db=f.db;const agent=request.agent(createApp(db));const login=await agent.post('/api/auth/login').send({email:'owner@test.co.ke',password:'test-password-strong'});const send=(body:any)=>agent.post('/api/sales').set('x-csrf-token',login.body.csrf).set('idempotency-key','test-key-checkout-001').send(body);const first=await send(saleInput(f.p,f.sessionId));expect(first.status).toBe(201);expect((await send(saleInput(f.p,f.sessionId))).body.id).toBe(first.body.id);expect((await send({...saleInput(f.p,f.sessionId),notes:'changed'})).status).toBe(409);expect(one(db,'SELECT COUNT(*) n FROM sales')!.n).toBe(1);});
});
